### ISSUE TITLE
Deployment fails with FiberError

### ISSUE THREAD

**Issue by chris-allen** [chris-allen/dream-ops#18]
```bash
/usr/local/bundle/gems/dream-ops-0.6.0/lib/dream-ops/deployment/solo.rb:23:in `next': fiber called across threads (FiberError)
	from /usr/local/bundle/gems/dream-ops-0.6.0/lib/dream-ops/deployment/solo.rb:23:in `rescue in __wait_for_pid'
	from /usr/local/bundle/gems/dream-ops-0.6.0/lib/dream-ops/deployment/solo.rb:16:in `__wait_for_pid'
	from /usr/local/bundle/gems/dream-ops-0.6.0/lib/dream-ops/deployment/solo.rb:175:in `run_chef_role'
	from /usr/local/bundle/gems/dream-ops-0.6.0/lib/dream-ops/deployment/solo.rb:211:in `deploy_target'
	from /usr/local/bundle/gems/dream-ops-0.6.0/lib/dream-ops/deployment/base.rb:130:in `block (2 levels) in deploy'
```

**Comment by chris-allen** [comment]
Verified fixed in `dream-ops@0.6.1`
