### ISSUE TITLE
Fail gracefully when not specifying an SHH identity file

### ISSUE THREAD

**Issue by chris-allen** [chris-allen/dream-ops#22]
**Observation:**
```bash
$ dream deploy solo -T ubuntu@example.com
/home/user/.rvm/gems/ruby-2.4.3/gems/dream-ops-0.7.0/lib/dream-ops/deployment/solo.rb:88:in `analyze_target': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /home/user/.rvm/gems/ruby-2.4.3/gems/dream-ops-0.7.0/lib/dream-ops/deployment/solo.rb:62:in `block in analyze'
	from /home/user/.rvm/gems/ruby-2.4.3/gems/dream-ops-0.7.0/lib/dream-ops/deployment/solo.rb:61:in `each'
	from /home/user/.rvm/gems/ruby-2.4.3/gems/dream-ops-0.7.0/lib/dream-ops/deployment/solo.rb:61:in `analyze'
	from /home/user/.rvm/gems/ruby-2.4.3/gems/dream-ops-0.7.0/lib/dream-ops/deployment/base.rb:116:in `deploy'
	from /home/user/.rvm/gems/ruby-2.4.3/gems/dream-ops-0.7.0/lib/dream-ops/cli.rb:144:in `deploy'
	from /home/user/.rvm/gems/ruby-2.4.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /home/user/.rvm/gems/ruby-2.4.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/user/.rvm/gems/ruby-2.4.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /home/user/.rvm/gems/ruby-2.4.3/gems/dream-ops-0.7.0/lib/dream-ops/cli.rb:46:in `dispatch'
	from /home/user/.rvm/gems/ruby-2.4.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /home/user/.rvm/gems/ruby-2.4.3/gems/dream-ops-0.7.0/lib/dream-ops/cli.rb:26:in `execute!'
	from /home/user/.rvm/gems/ruby-2.4.3/gems/dream-ops-0.7.0/exe/dream:5:in `<top (required)>'
	from /home/user/.rvm/gems/ruby-2.4.3/bin/dream:23:in `load'
	from /home/user/.rvm/gems/ruby-2.4.3/bin/dream:23:in `<main>'
```

**Expected Behavior:**
```bash
$ dream deploy solo -T ubuntu@example.com
You mush specify a SSH key for authentication.
```

**Comment by chris-allen** [comment]
This is slated to be released with `0.7.1`
